### ISSUE TITLE
Incorrect symlink handling by CharybdeFS

### ISSUE THREAD

**Issue by cheremin** [benoit-canet/charibefs#10]
There is and issue with symlink handling by charybdefs. Namely, you can't create symlink inside charybdefs-mounted folder. To reproduce it is enough to mount folder with charybdefs and try to make a symlink. 
Like this:
```
(inside charydbe-mounted folder)
>touch test
>ln -s test test-link
ln: failed to create symbolic link 'test-link': Input/output error
```
Interestingly, `test-link` **is** created, and it is really symlink to `test` (it reflects content of test, it reflects changes in `test` content), but it is shown **as regular file**:
```
>ls -alsh
total 8.0K
4.0K drwxrwxr-x 2 ubuntu ubuntu 4.0K May  7 17:03 .
4.0K drwxrwxr-x 4 ubuntu ubuntu 4.0K May  7 16:36 ..
   0 -rw-rw-r-- 1 ubuntu ubuntu    0 May  7 17:03 test
   0 -rw-rw-r-- 1 ubuntu ubuntu    0 May  7 17:03 test-link
```
Also, in data folder (on the top of which charydbe operates) `test-link` **is shown** as symlink to `test`:
```
>ls -alsh
total 8.0K
4.0K drwxrwxr-x 2 ubuntu ubuntu 4.0K May  7 17:03 .
4.0K drwxrwxr-x 4 ubuntu ubuntu 4.0K May  7 16:36 ..
   0 -rw-rw-r-- 1 ubuntu ubuntu    0 May  7 17:03 test
   0 lrwxrwxrwx 1 ubuntu ubuntu    4 May  7 17:03 test-link -> test
```

I've tried to run `ln` command with `strace`:
```
>rm test-link
>strace ln -s test test-link
...
symlink("test", "test-link")            = -1 EIO (Input/output error)
...
```
So it is indeed actual symlink syscall which returns error code. After I've spent some time looking for errors in `charybde_symlink` method, but with no success. After another round of digging around, I've come to something which looks like a solution: the root cause seems to be not in `charybde_symlink` method, but in `charybde_getattr`:
```
int charybde_getattr(const char *path, struct stat *buf)
{
    static volatile int in_flight = 0;
    in_flight++;
    int ret = error_inject(in_flight, path, "getattr");
    if (ret) {
        in_flight--;
        return ret;
    }

    ret = stat(path, buf);   // <<<< here it should be lstat, which provides correct handling of symlinks
    if (ret < 0) {
        in_flight--;
        return -errno;
    }
    
    in_flight--;
    return 0;    
}
```
I'm not expert in FUSE and linux IO in general, changing `stat` -> `lstat` in this method seems to fix the symlink handling:
```
>ln -s test test-link
>ls
4.0K drwxrwxr-x 2 ubuntu ubuntu 4.0K May  7 17:16 .
4.0K drwxrwxr-x 4 ubuntu ubuntu 4.0K May  7 16:36 ..
   0 -rw-rw-r-- 1 ubuntu ubuntu    0 May  7 17:03 test
   0 lrwxrwxrwx 1 ubuntu ubuntu    4 May  7 17:16 test-link -> test
```

**Comment by bentsi** [comment]
@cheremin Thanks for reporting this.

Indeed lstat syscall should be used.
The reason is because after `symlink` request, fuse automatically calls `getattr` [1] and 
under current implementation using `stat`, it stats the target of the link but not the link file itself.

[1] https://github.com/libfuse/libfuse/wiki/Invariants

**Comment by cheremin** [comment]
Thank you for fix and additional info!
