### ISSUE TITLE
Next incorrect symlink handling by CharybdeFS 

### ISSUE THREAD

**Issue by cheremin** [benoit-canet/charibefs#11]
It seems like there is another bug with symlinks in charybdefs. To reproduce it you need to create >1 symlinks, and linked files should have different filename lengths. E.g.
```
(mount charybdefs folder)
>touch test test-1111 test-2222-3333 
>ln -s test test.link
>ln -s test-1111 test-1111.link
>ln -s test-2222-3333 test-2222-3333.link
>ls -alsh
   0 -rw-rw-r-- 1 ubuntu ubuntu    0 May 10 17:50 test
   0 -rw-rw-r-- 1 ubuntu ubuntu    0 May 10 17:50 test-1111
   0 lrwxrwxrwx 1 ubuntu ubuntu    9 May 10 17:54 test-1111.link -> test-1111-3333 <<<< there is no such target!
   0 -rw-rw-r-- 1 ubuntu ubuntu    0 May 10 17:50 test-2222-3333
   0 lrwxrwxrwx 1 ubuntu ubuntu   14 May 10 17:53 test-2222-3333.link -> test-2222-3333
   0 lrwxrwxrwx 1 ubuntu ubuntu    4 May 10 17:54 test.link -> test-2222-3333
```
Even more interesting: subsequent `ls` will give different results: sometimes one link will target to non-existent filename, sometimes another, sometimes everything will looks fine.

It seems like issue is in `charybde_readlink`:
```
int charybde_readlink(const char *path, char *buf, size_t bufsiz)
{
    static volatile int in_flight = 0;
    in_flight++;
    int ret = error_inject(in_flight, path, "readlink");
    if (ret) {
        in_flight--;
        return ret;
    }

    ret = readlink(path, buf, bufsiz);
    if (ret < 0) {
        in_flight--;
        return -errno;
    }

    in_flight--;
    return 0;
}
``` 
There is mismatch between requirements: FUSE .readlink requires `*buf` to be returned as 0-terminated string, but `readlink` syscall doesn't terminate its 2-nd argument with 0, instead `readlink` returns how many chars were copied in `buf`. This is not manifested if there is only 1 symlinks -- probably, because FUSE zeroes `buf` before calling .readlink. But if there are >1 symlinks, and `buf` is reused -- you'll get  the behaviour observed.

I've tried to add `buf[ret]=0`:
```
int charybde_readlink(const char *path, char *buf, size_t bufsiz)
{
    static volatile int in_flight = 0;
    in_flight++;
    int ret = error_inject(in_flight, path, "readlink");
    if (ret) {
        in_flight--;
        return ret;
    }

    ret = readlink(path, buf, bufsiz);
    if (ret < 0) {
        in_flight--;
        return -errno;
    }
    buf[ret] = 0;   //<<<<<<

    in_flight--;
    return 0;
}
``` 
And it fix issue for me. 

But I'm not sure about corner case: what if `ret==bufsize`? I.e. what if there is no space for additional 0 in `buf`?

**Comment by bentsi** [comment]
@cheremin good catch and solution.
According to readlink syscall definition[1] and fuse readlink [2] when the link name is too long it should be truncated. So I think your solution is correct.

[1] http://man7.org/linux/man-pages/man2/readlink.2.html
[2] https://libfuse.github.io/doxygen/structfuse__operations.html#a0a7fe4e7fe5db55e96ef6adaf64c09e2

**Comment by cheremin** [comment]
Thank you!
