### ISSUE TITLE
Recommended Ubuntu packages don't exist

### ISSUE THREAD

**Issue by nh2** [benoit-canet/charibefs#12]
https://github.com/scylladb/charybdefs/tree/c55ab834569d3979ec69c090b43df7c02286a61a#building

```
% sudo apt-get install g++ cmake fuse libfuse-dev libthrift-dev python-thrift
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libthrift-dev
```

Ubuntu 16.04 does not have a package `libthrift-dev` as written in the README.

**Comment by db-vmw** [comment]
Hello,
Any update on the "libthrift-dev" package on ubuntu?
I get following error on executing cmake

`
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26")
-- Performing Test FUSE_CFLAGS_CHECK
-- Performing Test FUSE_CFLAGS_CHECK - Success
-- Found FUSE: /usr/lib/x86_64-linux-gnu/libfuse.so (found suitable version "2.9", minimum required is "2.9")
-- THRIFT_HOME:
-- Thrift version: Thrift version 0.9.1
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
THRIFT_INCLUDE_DIR (ADVANCED)
   used as include directory in directory <FILE_LOCATION>
   used as include directory in directory <FILE_LOCATION>
   used as include directory in directory <FILE_LOCATION>
   used as include directory in directory <FILE_LOCATION>
   used as include directory in directory <FILE_LOCATION>

-- Configuring incomplete, errors occurred!
`

**Comment by db-vmw** [comment]
@syuu1228 , Thanks for an update in the doc.
But, I see the following error when try to install the dependent packages (as described in the above change for readme.md).
`
sudo apt-get install g++ cmake fuse libfuse-dev python-thrift thrift-compiler scylla-libthrift010-dev libboost-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libboost-dev : Depends: libboost1.67-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`
